### ISSUE TITLE
请教如何关闭触控屏

### ISSUE THREAD

**Issue by jasonziai** [Tecyang/matebook142020-OpenCore-Hackintosh#3]
用过最舒服的一个efi。后来屏幕裂开了，触控乱跳乱点。尝试过不加载某些kext，连触摸板都给禁了。请问如何单独关闭触控屏幕功能？

**Comment by Tecyang** [comment]
目前触屏使用VoodooI2C驱动，使用DP注入，指定轮询模式为强制轮询进行工作。可以通过去除DP注入的PCI信息，使得VoodooI2C无法正常驱动触屏达到禁用的目的。
另外也可以通过ACPI禁用设备直接禁用，可参考ACPI
目录下SSDT-TPXX-MB14.aml（操作编辑ACPI有风险，请确保知道自己修改会产生什么后果）

PS：
触屏工作模式可以通过修改force-polling来切换，目前我机器测试中断模式及轮询模式均可以工作，且中断模式支持多指手势（与触控板一致），但是中断模式会造成CPU异常升高，所以EFI中默认是开启了强制轮询的。
<img width="1045" alt="iShot_2023-06-21_15 25 57" src="https://github.com/Tecyang/matebook142020-OpenCore-Hackintosh/assets/5939598/e196dda0-a278-444e-a6a7-1018ceda4c9d">
<img width="1023" alt="image" src="https://github.com/Tecyang/matebook142020-OpenCore-Hackintosh/assets/5939598/03e2f1e0-28f0-4837-8713-f0b0d9a2850d">

**Comment by jasonziai** [comment]
非常感谢，删了DP注入就好了。
